default:
  dora_dir: /data/lw/musci_generation/gvmgen/output
  partitions:
    global: debug
    team: debug
  reference_dir: /data/lw/musci_generation/gvmgen/GVMGen-main/checkpoints
darwin:  # if we detect we are on a Mac, then most likely we are doing unit testing etc.
  dora_dir: path/to/your_dir
  partitions:
    global: debug
    team: debug
  reference_dir: path/to/your_dir

